### ISSUE TITLE
Chrome doesn't like http://neo4j-contrib.github.io/developer-resources/language-guides/assets/css/main.css

### ISSUE THREAD

**Issue by ttocskcaj** [OpenPolytechnicBITProjectGroup/Musician-Venue_App#3]
Chrome is giving me an error:
`morning-escarpment-88913.herokuapp.com/:5 Mixed Content: The page at 'https://morning-escarpment-88913.herokuapp.com/' was loaded over HTTPS, but requested an insecure stylesheet 'http://neo4j-contrib.github.io/developer-resources/language-guides/assets/css/main.css'. This request has been blocked; the content must be served over HTTPS.`

I suggest we install bootstrap from NPM and use that version, or use a CDN that has https to keep the browser happy.

**Comment by lxdnz254** [comment]
Change it to https ... oops I missed that
