### ISSUE TITLE
Coverflow for venue and artist cards

### ISSUE THREAD

**Issue by lxdnz254** [OpenPolytechnicBITProjectGroup/Musician-Venue_App#34]
I have been looking for angular solutions to creating a CoverFlow output for artists and venues.
So far I have [found this implementation](https://gist.github.com/lxdnz254/af986946758d480700f3ff999acd79ed)  
Which, with a bit of re-factoring in the code, could suit our purposes.

**Comment by ttocskcaj** [comment]
I think using something like https://github.com/drien/jquery-flipster would be better. Maybe combining the two to incorporate it into angular.

This one is touch enabled which is important for phones.

**Comment by lxdnz254** [comment]
That looks quite cool, would we write flicker.js into package.js or keep it as a separate module that only loads on page's we want it on? I.e. venues.html & artists.html
