### ISSUE TITLE
Search expects genre

### ISSUE THREAD

**Issue by lxdnz254** [OpenPolytechnicBITProjectGroup/Musician-Venue_App#36]
A small issue to solve.
`/api/search` expects a "genre" variable, we need to set a default if no "genre" is selected.
![image](https://user-images.githubusercontent.com/8147138/29051643-4a9034ee-7c38-11e7-8dbe-72705b52fba4.png)

Should be a relatively simple fix.

**Comment by ttocskcaj** [comment]
I'll fix this evening. Was gonna do a bit more API work.

**Comment by lxdnz254** [comment]
Looking at the initial requirements we should return "No search query entered"

**Comment by ttocskcaj** [comment]
At the same time, should we be able to search for multiple genres? 
E.G. searching for a pub that likes both hiphop and metalcore music?

**Comment by lxdnz254** [comment]
Multiple genre search would be cool.
If you can find a pub that likes hip hop and metalcore WOW!

**Comment by ttocskcaj** [comment]
Only the best pubs do :p
